### ISSUE TITLE
PMTCT Home page

### ISSUE THREAD

**Issue by muyaso** [SoftmedTanzania/opensrp-client-chw-hf#1019]
[ ] "PMTCT home page" still shows the client is" overdue "even if the visit is recorded,And the client still remains in the "missed button" list

**Comment by muyaso** [comment]
same goes if the client was a lost to follow up or transfer out and  the client visit was just  conducted it still reflect previous status-it should be **visit done**

**Comment by cozej4** [comment]
This is only going to get updated once the event are processed after 24 hours.

@muyaso please confirm if this works as intended

**Comment by muyaso** [comment]
confirmed
