### ISSUE TITLE
KVP Screening for female clients aged 15-24 misses AGYW screening

### ISSUE THREAD

**Issue by dianamayala** [SoftmedTanzania/opensrp-client-chw-hf#1026]
During screening afer FSW screening for female client's aged 15-24 misses when next is selected it should go to the AGYW screening page since they can also fall in the AGYW category. Now they skip to "Other Vulnerable population screening"

**Comment by dev-billy** [comment]
@dianamayala shouldn't the range for agyw be 10-24

**Comment by dianamayala** [comment]
> @dianamayala shouldn't the range for agyw be 10-24

From the KVP tool it uses 15-24
![WhatsApp Image 2022-10-19 at 15 18 07](https://user-images.githubusercontent.com/113107339/196691193-cdb1b832-631b-4dbd-bde9-921b52ed58e8.jpeg)
