### ISSUE TITLE
"Follow up status form "should not appear for the client who is newly diagnosed as an HIV client

### ISSUE THREAD

**Issue by muyaso** [SoftmedTanzania/opensrp-client-chw-hf#1203]
- [ ] the forms should appear for follow up client only

**Comment by cozej4** [comment]
@muyaso.  I would disagree with this. Is this from the health providers using the Pilot APK??

**Comment by cozej4** [comment]
@muyaso. Plus how would you calculate indicator G3 for clients who only had the first visit?



![Image](https://user-images.githubusercontent.com/9714534/211494121-85cb0ff1-ed34-432d-beb5-e91052db1521.png)

**Comment by muyaso** [comment]
for a new client to have a follow up status form which contain LTF,TO and CTN it just doesn't add up,a client can not be new and be a CTN or LTF
As for  G3 the PMTCT visit 0 should be incorporated with CTN M2 or M3 for it to reflect
But if the risk are too HIGH  just  leave it.....,..we will explain it

**Comment by cozej4** [comment]
What if the client was not given services on that first day. Again, this will remain as is
