### ISSUE TITLE
Update Vaginal Examination Component

### ISSUE THREAD

**Issue by issyzac** [SoftmedTanzania/opensrp-client-chw-hf#269]
- [x]  Cervix State

- Soft and Thin
- Replace **Hard** with **Thick**

- [x]  Presenting part affects Position

- Vertex - Occiput
- Breech - To be Provided
- Brow - TBP
- Shoulder - TBP
- Face - TBP
- Cord - TBP

- [x]  Position Occiput

- Remove the extra "occiput" in OPP

- [x]  First stage-vaginal examination form-add the position of the presenting part according to the selection of the presenting part

 

- [x] Face Presentation

-Right mentoposterior(RMP)
-Left mentaposterior(LMP)
-Right mentolateral(RML)
-Left mentolateral(LML)
-Right mentoanterior(RMA)
-Left mentanterior(LMA)

- [x] Breech Presentation

-Right Sacroposterior(RSP)
-Left Sacroposterior(LSP)
-Right sacrolateral(RSL)
-Left sacrolateral(LSL)
-Right sacroanterior(RSA)
-Left sacroanterior(LSA)

- [x] Vertex Presentation

-Left Occipito anterior(LOA)
-Right occipito anterior(ROA)
-Left occipitolateral(LOL)
-Right Occipitolateral(ROL)
-Left occipitoposterior(LOP)
-Right Occipitoposterior(ROP)
-Direct occipito anterior(DOA)
-Direct occipito posterior(DOP)

- [x] Shoulder presentation

-Dorso anterior
-Dorso posterior

**Comment by issyzac** [comment]
@cozej4 Did we receive the To Be Provided fields?

**Comment by cozej4** [comment]
@issyzac  No, not yet

**Comment by victormanase** [comment]
@issyzac @cozej4  i have updated the position of the presenting part according to the selection based on the option from mama izengo
