### ISSUE TITLE
Update workflow when cervix dilation is less that 3

### ISSUE THREAD

**Issue by issyzac** [SoftmedTanzania/opensrp-client-chw-hf#270]
If cervix dilation is less than 3 repeat the entire examination process
- General Examination
- Vaginal Examination

**Comment by muyaso** [comment]
- [ ] the second vaginal assessment indicate Partially complete and  yellow tick  but the forms can be submitted ,After submiting  see the attachment below
- [ ] for the second examination exclude HIV test/malaria test e.t.c if they are already conducted on the first 


![Image](https://user-images.githubusercontent.com/107064455/181457635-ed1b6604-6465-40f8-a711-ffb8be570d7b.jpg)
