### ISSUE TITLE
Update True Labor

### ISSUE THREAD

**Issue by issyzac** [SoftmedTanzania/opensrp-client-chw-hf#299]
- [x] Update text

Regular uterine constructions with increasing frequency and duration

**Comment by muyaso** [comment]
rephrase the true labour sign''Painful,increasing frequency and duration '' to ''regular painful uterine contraction with increasing frequency and duration''

**Comment by muyaso** [comment]
rephrase the true labour sign''Painful,increasing frequency and duration '' to ''regular painful uterine contraction with increasing frequency and duration''
