### ISSUE TITLE
Update Obstetric History

### ISSUE THREAD

**Issue by issyzac** [SoftmedTanzania/opensrp-client-chw-hf#301]
- [x] Para should be less than gravida

- [x] Number of abortions should also be less than gravida

- [ ] Number of abortion should be positioned higher than number of children
- [x] Past medical /surgical history should be pulled from ANC visit by the system(automatical filled)

**Comment by muyaso** [comment]
- [ ] number of abortion should be less than gravida,Currently number of abortion is less than or equal to gravida
- [ ] if para is 0,then number of living should also be 0
- [ ] past medical/surgical history should pop up for all client, and not only for client who are Gravida 2 and above

**Comment by cozej4** [comment]
@muyaso Can you explain more on this `past medical/surgical history should pop up for all clients, and not only for clients who are Gravida 2 and above`

It doesn't seem to make sense

**Comment by cozej4** [comment]
@muyaso  past medical/surgical history  only captures past PARA details and a client with Gravida 1 won't have any para, hence no need to display the action

**Comment by cozej4** [comment]
@muyaso  based on the agreed upon implementation, past medical/surgical history  only captures past PARA details and a client with Gravida 1 won't have any para, hence no need to display the action

**Comment by muyaso** [comment]
past Para details is captured in past obstetric history form while past medical and surgical history captures informations that are not related to uzazi example heart disease, asthma, diabetes which can have impact during delivery if not captured

**Comment by cozej4** [comment]
@muyaso  Your explanation is still not clear enough on what is required. Can you add screenshots of what the comment describes

**Comment by muyaso** [comment]
the question of past medical and surgical history should be there regardless of the parity or gravid.
the screenshot is from  first ANC visit
![Screenshot_20230505-093548](https://user-images.githubusercontent.com/107064455/180170650-fc5
![Screenshot_20230505-093610](https://user-images.githubusercontent.com/107064455/180170896-1ac991dd-43ff-43a0-967e-07d50f5aa241.png)
5aca6-a1b9-4776-b19f-1c047ccc460d.png)

**Comment by muyaso** [comment]
![Screenshot_20230505-093548](https://user-images.githubusercontent.com/107064455/180171382-2bbf179e-be83-461c-8624-0a56a94caa9b.png)
