### ISSUE TITLE
Update Past Obstetric History

### ISSUE THREAD

**Issue by issyzac** [SoftmedTanzania/opensrp-client-chw-hf#302]
- [x] In the complications add Others option

- [x] Add complication - IUFD

- [x] If children born alive is NO specify reason

- [ ]  parity should be arranged in sequence i.e according to the year the child was born from the first to the last and not randomly arranged

**Comment by issyzac** [comment]
@cozej4 the last item does not make a lot of sense,  is it an issue of arranging after it was entered or entering in sequence? Also keeping in mind that the section is for data capture only, if the information needs to be there for future references it means it be at a different place displayed differently (arranged if need be)

**Comment by cozej4** [comment]
@issyzac I agree, that this does not make sense since it's dependent on the provider's input sequence. Lets have this closed

**Comment by issyzac** [comment]
@cozej4 sawa, am going to close this for now
