### ISSUE TITLE
Vaginal Examination

### ISSUE THREAD

**Issue by issyzac** [SoftmedTanzania/opensrp-client-chw-hf#308]
- [x] If presenting part is Breech, add option NA in moulding
- [x] Everything is filled in action but it still shows partially completed
- [x] Remove position of occiput in determining the status of an action
- [x] If cervix dilatation is < 3 add prompt to continue routine examination
- [x] Vagina Assessment instead of Vagina examination
- [x] Ordering of Vagina Assessment should be Intact , tear ,bleeding
- [x] Intact and Tear should not be allowed on the combination of options on the multi select.
- [x] Vaginal Bleeding 👉  Prompt to appear if the abnormal option is selected.
- [x] incase moulding is ++ or +++ put prompt
- [x] If membrane have ruptured and the  amniotic fluid is clear remove the prompt 
- [x] Form is indicated as partially completed when all option other than Vertex is selected

**Comment by muyaso** [comment]
if membrane have ruptured and the amniotic fluid is clear the prompt still appears
