### ISSUE TITLE
PARTOGRAPH : Progress of Labor

### ISSUE THREAD

**Issue by issyzac** [SoftmedTanzania/opensrp-client-chw-hf#312]
- [x] Cervix dilation scale should not be above 10
- [x] Head of descent should also have a prompt if the descent is slower than expected based on the formula below
- [x] Head descent formula
       - should descend 1 unit every 4 hours
 

- [x] omit the word FETAL  progrees of labour to'' progress of labour ''from the form tittle

- [x] add asterisk for pulse rate as its checked every half an hour

**Comment by muyaso** [comment]
asterisk for pulse rate not added

**Comment by muyaso** [comment]
- [x] Head descent formula
       - should descend 1 unit every 4 hours
       -if no progress Add prompt(ALERT;closer monitoring is required for this client)
