### ISSUE TITLE
PARTOGRAPH : Chart

### ISSUE THREAD

**Issue by issyzac** [SoftmedTanzania/opensrp-client-chw-hf#315]
Graphs to be added

- [x] Contractions graph
- [x] Liquor/Moulding/Caput graph
- [ ] Oxytocin graph
- [x] Pulse and Blood pressure graph
- [x] Temperature chart
- [x] Urine protein/acetone/volume/oral intake chart

**Comment by muyaso** [comment]
There is no oral intake chart in the partograph

**Comment by cozej4** [comment]
@muyaso What do you mean by this?

**Comment by muyaso** [comment]
The last part of the graph has urine protein,urine acetone,urine volume,But  there is no oral intake chart which is also supposed to be among them.

**Comment by cozej4** [comment]
@muyaso Does your copy of the partograph have this?
If so please share the scanned copy of the patograph

**Comment by muyaso** [comment]
![](https://files.slack.com/files-pri/T03DAM2E1EJ-F03HNCPFS9Y/image_from_ios.jpg)

**Comment by muyaso** [comment]
![Image from iOS](https://user-images.githubusercontent.com/107064455/179993430-da0c9830-1cff-4269-b286-dde4cdfb07a9.jpg)
