### ISSUE TITLE
The form for treatment during labour should not be mandatory to be filled once its opened.

### ISSUE THREAD

**Issue by issyzac** [SoftmedTanzania/opensrp-client-chw-hf#320]
- [x] oxytocine drop /min add a text panel asking ''drops/mins given''

- [x] during editing treatment form display as green ticked when opening it ,its not filled 
- [x] 'treatment given during labour ''does not appear on partograph details

**Comment by issyzac** [comment]
@cozej4 Is this still the case on the last item?

**Comment by cozej4** [comment]
@issyzac, This is a duplicate issue. This is already resolved in this [issue](https://github.com/SoftmedTanzania/opensrp-client-chw-hf/issues/361)
