### ISSUE TITLE
If caesarean section is chosen, a panel should appear below asking for reasons why

### ISSUE THREAD

**Issue by issyzac** [SoftmedTanzania/opensrp-client-chw-hf#323]
- [x] reasons                                        
- fetal distres
- Previous scare
- Maternal request
- Failed induction
- Malpresentation
- Prolonged labor
- obstructed labor
- Multiple gastation               
- Others specify"

- [x] If option for caesarian is selected, the system does not progress to the next stage of Labour management

**Comment by gosso22** [comment]
@issyzac and @cozej4 - I am not sure what is required for the second task here. Currently when they choose caesarean as a method of delivery the system takes them to the procedure "Mother Post Delivery Management" skipping the 3rd Stage.

**Comment by issyzac** [comment]
Ooh okay, so my understanding of this is that before the process went straight to the Post delivery management but now it needs to ask the reasons first before going to that stage, in terms of process flow it should go straight to the same process but now there will just be an extra question asking the user what are the reasons for cesarean before going to the process that follows
