### ISSUE TITLE
Update Method of Delivery.

### ISSUE THREAD

**Issue by cozej4** [SoftmedTanzania/opensrp-client-chw-hf#326]
- [x] Update **Instrumental Delivery** to **Vacuum Extraction** 

- [x] Add **Breech Delivery**

**Comment by gosso22** [comment]
There is Method of Delivery in Obstetric History, do we need to update this as well?

**Comment by cozej4** [comment]
@gosso22 Yeah, we should also update that to include the Breech Delivery and update Instrumental Delivery to Vacuum Extraction
