### ISSUE TITLE
Button going back to the patograph doesn't work

### ISSUE THREAD

**Issue by issyzac** [SoftmedTanzania/opensrp-client-chw-hf#329]
- [ ] Going from the partograph chart back to the profile of the mother the button does not work

- [ ] the X should touch the alert line and not the 0
- [ ] there are two lines drawn in the graph in both descent,dilation,FHR

**Comment by muyaso** [comment]
![Image](https://user-images.githubusercontent.com/107064455/172589917-48e42ea2-675d-4620-8585-8edddc1b4f5c.jpeg)
