### ISSUE TITLE
For HB and HIV tests, if the last date of testing was more than three months ago for PMTCT and 2 weeks ago for HB, then there should be a panel that allows a repeat of the respective test.

### ISSUE THREAD

**Issue by issyzac** [SoftmedTanzania/opensrp-client-chw-hf#337]
- [x] Three months limit for HIV Test
- [x] Two weeks limit for HB Test

**Comment by issyzac** [comment]
@cozej4 
Do we have HB test date captured before the delivery date? Like ANC? I saw `hb_level` is being captured in ANC but not sure if its being captured together with the date

**Comment by cozej4** [comment]
Yes, we have the field called `hb_test_date` captured in the form [`labour_and_delivery_registration_anc_clinic_findings.json`](https://github.com/SoftmedTanzania/opensrp-client-chw-hf/blob/0976c484bba5f3c6848cd574ab006448676fe8dd/opensrp-chw-hf/src/main/assets/json.form/labour_and_delivery_registration_anc_clinic_findings.json#L203)

**Comment by issyzac** [comment]
Oh so its the same date that is entered in that form. Got it. Initially I thought its to be fetched from other medical records
