### ISSUE TITLE
TB Screening on ANC Visit

### ISSUE THREAD

**Issue by Kasika-S** [SoftmedTanzania/opensrp-client-chw-hf#471]
On the TB screening form for ANC clients, Cough symptoms for HIV-positive clients should be changed to **Cough of any duration**, not only 2 weeks

**Comment by Kasika-S** [comment]
@zk497 Do you need any clarification?

**Comment by zk497** [comment]
@Kasika-S After our previous conversation, no. In case additional information is required, I will contact you.
