### ISSUE TITLE
ANC Clients

### ISSUE THREAD

**Issue by zk497** [SoftmedTanzania/opensrp-client-chw-hf#499]
Clients enrolled in ANC in the WAJA application, appear as Independent clients in the Kituoni application.

**Comment by cozej4** [comment]
@zk497 I don't believe that this is an issue, if the client has never visited the Health Facility for her ANC Clinic

**Comment by cozej4** [comment]
@victormanase Is this really a bug?

**Comment by victormanase** [comment]
@cozej4  this is not an issue

**Comment by zk497** [comment]
@cozej4 @victormanase, I registered an independent client in the Community application and then enrolled the client to ANC in the community application. When I synced the client to appear in the Facility app, the client appeared as an Independent client. However, I tested it out today to re-check and it works, the client appeared as an ANC client in the Facility application. Should I close this issue?
