### ISSUE TITLE
LD Registration

### ISSUE THREAD

**Issue by zk497** [SoftmedTanzania/opensrp-client-chw-hf#568]
It is possible to register a client to the L&D module after just completing the first two actions and without completing the rest of the actions.

**Comment by zk497** [comment]
- From the screenshot below it is visible that the `submit` button can be clicked before completing the remaining actions. 

![Screenshot_1658840698](https://user-images.githubusercontent.com/58561265/181013462-ac82c7d0-fd53-4570-8e33-93a50c053a9e.png)

**Comment by cozej4** [comment]
@zk497 Thanks for the observation. I'll take a look at this
