### ISSUE TITLE
HIV Testing Service Module

### ISSUE THREAD

**Issue by cozej4** [SoftmedTanzania/opensrp-client-chw-hf#635]
- [x] If client is found to be HIV positive, and has not been enrolled to CTC, there should be a prompt saying, ‘**Refer the client to CTC for verification and enrollment**'

**Comment by muyaso** [comment]
- [ ] No prompt (index contact HIV outcome form) if the client is not enrolled to CTC

**Comment by zk497** [comment]
@muyaso as discussed yesterday, this is supposed to be created as a new issue, as the original issue is not the one that is mentioned above.

**Comment by muyaso** [comment]
sawa
