### ISSUE TITLE
HEI Number

### ISSUE THREAD

**Issue by Kasika-S** [SoftmedTanzania/opensrp-client-chw-hf#650]
- [x] The HEI number displayed in the profile page of the HEI client does not follow the format shown when writing the number, i.e: it does not have a C in between the numbers

**Comment by cozej4** [comment]
@Kasika-S Please provide the full format for the HEI Number

**Comment by Kasika-S** [comment]
The Format should be as follows ; CTC Number of the mother-C00 whereby 00 represents digits from 0 through 9.

Note: C00 represents the chronological order of the child's birth. 
eg 
- [ ] C01 - First Born
- [ ] C02 - Second Born
