### ISSUE TITLE
immediately post partum care

### ISSUE THREAD

**Issue by cozej4** [SoftmedTanzania/opensrp-client-chw-hf#654]
client name- E E 
Elective C/S pt
user agaktwo
the profile state ''L&D still in progress"when edit button clicked the forms are displayed as below
The APP crushed, then it crushes when logging in

![Image](https://user-images.githubusercontent.com/107064455/187094853-644ba9f3-84bc-46ce-a347-5bdfd06d2539.jpg)

**Comment by cozej4** [comment]
@muyaso I can not recreate this issue on my end

**Comment by cozej4** [comment]
Is this with the latest APK? 
@Kasika-S Please test this on your end and see if you are experiencing this

**Comment by cozej4** [comment]
@muyaso That client does not exist, when login in using your username

**Comment by muyaso** [comment]
I can't  see her Pia,
