### ISSUE TITLE
EAC HVL Results Form

### ISSUE THREAD

**Issue by Kasika-S** [SoftmedTanzania/opensrp-client-chw-hf#665]
The prompt that appears for repeat HVL test when HVL results are  greater than or equal to 1000 copies after EAC sessions should be removed

**Comment by dev-billy** [comment]
@Kasika-S  the prompt "Repeat HVL after 6, 12 and 18 months"  test only shows up when the HVL results are less than 1000 copies. Can you please verify if that's the case and if that should be changed

**Comment by Kasika-S** [comment]
The prompt should read "Discuss The Plan for this Patient"

**Comment by dev-billy** [comment]
@Kasika-S  Please provide the translations for the prompt

**Comment by Kasika-S** [comment]
"Jadili Mpango wa matibabu ya Mteja Huyu"
