### ISSUE TITLE
PNC Visit - No Mother Children

### ISSUE THREAD

**Issue by Kasika-S** [SoftmedTanzania/opensrp-client-chw-hf#705]
During PNC Visit of Motherless Infant, there should be question for HIV status and it should be placed below the "HB Level Test " and it should read as follows;

HIV Antibody Test
- [ ] Positive
- [ ] Negative

If **Positive**, the Infant should be also automatically be registered in the HEI module, but if **Negative** they should stay in the PNC module then they will be transferred to the Child Clients Module after 42 days.

**Comment by muyaso** [comment]
- [ ] not implemented

**Comment by cozej4** [comment]
@muyaso THis has been implemented today. Please wait for a new APK

**Comment by cozej4** [comment]
@muyaso THis has been implemented today. Please wait for a new APK
