### ISSUE TITLE
HEI Client's Profile

### ISSUE THREAD

**Issue by Kasika-S** [SoftmedTanzania/opensrp-client-chw-hf#708]
On the HEI Module, for every HEI child listed, the name of the mother should also appear below the name of the Infant

**Comment by cozej4** [comment]
Also add mother details in the HEI profile including mother's CTC number

**Comment by dev-billy** [comment]
@cozej4 was wondering if the child's HEI number is the mother's CTC number with the -CXX is there a reason we should display both numbers for the mother and the child on the HEI profile?

**Comment by Kasika-S** [comment]
@dev-billy lets leave it as it is for now. I am closing the issue
