### ISSUE TITLE
PMTCT Inapp Reports(3-months) - B3c

### ISSUE THREAD

**Issue by Kasika-S** [SoftmedTanzania/opensrp-client-chw-hf#812]
The following Indicator does not reflect

- [ ] B3c - Idadi umri wa miaka 20-24

**Comment by cozej4** [comment]
@muyaso Please assist in confirming this

**Comment by cozej4** [comment]
@Kasika-S Please also confirm if this is the case

**Comment by Kasika-S** [comment]
It has been clarified
