### ISSUE TITLE
PNC Pregnancy Outcome - OPV 0 vaccine

### ISSUE THREAD

**Issue by cozej4** [SoftmedTanzania/opensrp-client-chw-hf#837]
For the Question regarding If OPV 0 vaccination was administered, if NO is selected then the prompt that appears should read as follows 
**"Provide OPV 0 vaccination to the infant at the first Postnatal care visit or as soon as the OPV 0 vaccine will be available. OPV 0 should not be provided beyond 14 days"**

**Comment by zk497** [comment]
@Kasika-S @muyaso Please provide the translation.

**Comment by muyaso** [comment]
''Mpatie chanjo ya OPV 0 mtoto kwenye udhurio la kwanza la baada ya kujifungua(PNC) au mara tu chanjo ya OPV 0 itakapo kuwepo.OPV 0 haitakiwi kutolewa baada ya mtoto kufikisha siku 14"
