### ISSUE TITLE
EID Cross-sectional Report - I & I1

### ISSUE THREAD

**Issue by Kasika-S** [SoftmedTanzania/opensrp-client-chw-hf#843]
- [x] I - Idadi ya watoto waliopima kipimo cha marudio wiki 12 baada ya kuacha kunyonya
- [x] I1 - dadi ya watoto waliogundulika kuwa na VVU kipimo wiki 12 baada ya kuacha kunyonya

The above Indicators do not reflect

**Comment by cozej4** [comment]
@Kasika-S This requires review

**Comment by Kasika-S** [comment]
Noted
