### ISSUE TITLE
Add Text field When Option "Others (Specify) is Selected

### ISSUE THREAD

**Issue by Kasika-S** [SoftmedTanzania/opensrp-client-chw-hf#940]
Add Text field When Option "Others (Specify) is Selected. This should apply to the following Questions

- [x] PrEP Side Effects
- [x] Other services/referrals provided to the client
- [x] Previous HIV testing method
- [x] PrEP Other Services and referral

**Comment by dianamayala** [comment]
The below still dont display Text field when others is selected
 PrEP Side Effect
 KVP Visit-Other services/referrals provided to the client 
 PrEP Other Services and referral
